### ISSUE TITLE
java.lang.ClassNotFoundException: io.confluent.kafka.security.ldap.authorizer.LdapAuthorizer

### ISSUE THREAD

**Issue by quanghn96** [Dabz/kafka-security-playbook#54]
I am having this problem when using LDAP. I use server.properties in this repositoy

```
[2020-05-22 04:39:49,183] ERROR Fatal error during SupportedServerStartable startup. Prepare to shutdown (io.confluent.support.metrics.SupportedKafka)
java.lang.ClassNotFoundException: io.confluent.kafka.security.ldap.authorizer.LdapAuthorizer
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.kafka.common.utils.Utils.loadClass(Utils.java:335)
	at org.apache.kafka.common.utils.Utils.newInstance(Utils.java:324)
	at kafka.security.authorizer.AuthorizerUtils$.createAuthorizer(AuthorizerUtils.scala:35)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1382)
	at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1238)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1218)
	at kafka.server.KafkaConfig$.fromProps(KafkaConfig.scala:1215)
	at kafka.server.KafkaConfig.fromProps(KafkaConfig.scala)
	at io.confluent.support.metrics.SupportedServerStartable.<init>(SupportedServerStartable.java:52)
	at io.confluent.support.metrics.SupportedKafka.main(SupportedKafka.java:45)

```

**Comment by Dabz** [comment]
Hi @quanghn96 ! Do you have the issue in a specific example? 
This error seems to be due that confluent-community is installed instead of confluent-server.
LdapAuthorizer is only in confluent-server.
